EMAIL_SERVICE: spendgrid
spendgrid:
  url: https://bw-interviews.herokuapp.com/spendgrid/send_email
  api_key: api_key_pADwCsjCtFEmUc30cNjN3q7r
snailgun:
  url: https://bw-interviews.herokuapp.com/snailgun/send_email
  api_key: api_key_y2W3sENFVzLike8jpBcLYMib
PORT: 3001